version: "3.1"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: yurii
      MONGO_INITDB_ROOT_PASSWORD: yurii
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: yurii
      ME_CONFIG_MONGODB_ADMINPASSWORD: yurii
      ME_CONFIG_MONGODB_URL: mongodb://yurii:yurii@mongo:27017/

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yurii
    ports:
      - 3306:3306
    volumes: 
      - type: bind
        source: D:/Projects/YouTubeDownloader/back/auth/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: yurii
      RABBITMQ_DEFAULT_PASS: yurii