name: Release Frontend Image
on:
  push:
    branches:
      - 'main'
    paths:
      - 'front/**'
  workflow_dispatch:
    inputs:
      gateway_url:
        description: "URL of the gateway that must be used in the Docker image"
        required: true
        default: "http://localhost:8080"

      server_side_gateway_url:
        description: "URL of the gateway (which will be accessed from server side) that must be used in the Docker image"
        required: false
        default: "http://gateway:8080"

jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
          
      - uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3.1.0
        with:
          images: alieksieiev/yt-downloader-frontend
          
      - name: Create .env.local
        run: |
          ss_gateway_url="${{ github.event.inputs.server_side_gateway_url }}"
          
          if [ "$ss_gateway_url" != "" ]; then
            echo NEXT_PUBLIC_SERVER_SIDE_GATEWAY_URL=$ss_gateway_url >> .env.local
          fi
            
          echo NEXT_PUBLIC_GATEWAY_URL=${{ github.event.inputs.gateway_url }} >> .env.local
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.0
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
