name: Release Frontend Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'front/**'
  workflow_dispatch:

jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
          
      - uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3.1.0
        with:
          images: alieksieiev/yt-downloader-frontend
          
      - name: Create .env.local
        run: |
          echo NEXT_PUBLIC_GATEWAY_URL=http://localhost:8080 >> .env.local
          echo NEXT_PUBLIC_SERVER_SIDE_GATEWAY_URL=http://gateway:8080 >> .env.local

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.0
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
